import type { Role } from "@prisma/client";
import { authorize } from "../middleware/authorize";

export const PERMISSIONS = {
  PROJECT_WRITE: ["CLIENT", "ADMIN"],
  MILESTONE_WRITE: ["CLIENT", "ADMIN"],
  EVIDENCE_UPLOAD: ["CONTRACTOR", "ADMIN"],
  EVIDENCE_READ: [
    "ADMIN",
    "AUDITOR",
    "PROCUREMENT_OFFICER",
    "CONTRACTOR",
    "CONSULTANT_ENGINEER",
    "CLIENT",
  ],
  VERIFY_INTERNAL: [
    "ADMIN",
    "AUDITOR",
    "PROCUREMENT_OFFICER",
    "CONSULTANT_ENGINEER",
  ],
  ATTEST: ["CONSULTANT_ENGINEER", "CLIENT", "PROCUREMENT_OFFICER", "AUDITOR", "ADMIN"],
  DISPUTE_CREATE: ["CONTRACTOR", "ADMIN", "CLIENT", "CONSULTANT_ENGINEER"],
  DISPUTE_READ: [
    "ADMIN",
    "AUDITOR",
    "PROCUREMENT_OFFICER",
    "CONTRACTOR",
    "CONSULTANT_ENGINEER",
    "CLIENT",
  ],
  DISPUTE_RESOLVE: ["ADMIN", "AUDITOR", "PROCUREMENT_OFFICER"],
  CORRECTION_CREATE: ["CONTRACTOR", "ADMIN", "CLIENT", "CONSULTANT_ENGINEER"],
  CORRECTION_READ: [
    "ADMIN",
    "AUDITOR",
    "PROCUREMENT_OFFICER",
    "CONTRACTOR",
    "CONSULTANT_ENGINEER",
    "CLIENT",
  ],
  CORRECTION_RESOLVE: ["ADMIN", "AUDITOR", "PROCUREMENT_OFFICER"],
  VARIATION_CREATE: ["CONTRACTOR", "ADMIN"],
  VARIATION_READ: ["ADMIN", "AUDITOR", "PROCUREMENT_OFFICER", "CONTRACTOR", "CLIENT"],
  VARIATION_RESOLVE: ["ADMIN", "AUDITOR", "PROCUREMENT_OFFICER"],
  /// Run a CRB registration check. Deliberately excludes CONTRACTOR: a
  /// contractor may read their own status but may not initiate checks.
  CRB_VERIFY: ["CLIENT", "CONSULTANT_ENGINEER", "PROCUREMENT_OFFICER", "AUDITOR", "ADMIN"],
  /// Read recorded CRB status, including a contractor's own record.
  CRB_READ: [
    "CONTRACTOR",
    "CLIENT",
    "CONSULTANT_ENGINEER",
    "PROCUREMENT_OFFICER",
    "AUDITOR",
    "ADMIN",
  ],
  PROCUREMENT_READ: ["CONTRACTOR", "CLIENT", "ADMIN", "AUDITOR", "PROCUREMENT_OFFICER"],
  PROCUREMENT_SYNC: ["ADMIN", "PROCUREMENT_OFFICER"],
  PROCUREMENT_LINK: ["ADMIN", "PROCUREMENT_OFFICER"],
  PROVISION_USERS: ["ADMIN"],
  AUDIT_READ: ["AUDITOR", "ADMIN", "PROCUREMENT_OFFICER"],
} as const satisfies Record<string, readonly Role[]>;

export type Permission = keyof typeof PERMISSIONS;

export function requirePermission(permission: Permission) {
  return authorize(...PERMISSIONS[permission]);
}
