export const BLOCKCHAIN_ERROR_CODES = {
  NOT_CONFIGURED: "BLOCKCHAIN_NOT_CONFIGURED",
  INVALID_HASH: "BLOCKCHAIN_INVALID_HASH",
  INVALID_ID: "BLOCKCHAIN_INVALID_ID",
  WRONG_NETWORK: "BLOCKCHAIN_WRONG_NETWORK",
  WRONG_CONTRACT: "BLOCKCHAIN_WRONG_CONTRACT",
  SIGNER_UNAVAILABLE: "BLOCKCHAIN_SIGNER_UNAVAILABLE",
  PROVIDER_FAILURE: "BLOCKCHAIN_PROVIDER_FAILURE",
  TRANSACTION_FAILED: "BLOCKCHAIN_TRANSACTION_FAILED",
  CONFIRMATION_FAILED: "BLOCKCHAIN_CONFIRMATION_FAILED",
  DUPLICATE_PROOF: "BLOCKCHAIN_DUPLICATE_PROOF",
  EVENT_MISMATCH: "BLOCKCHAIN_EVENT_MISMATCH",
} as const;

export class BlockchainError extends Error {
  constructor(
    public readonly code: (typeof BLOCKCHAIN_ERROR_CODES)[keyof typeof BLOCKCHAIN_ERROR_CODES],
    message: string,
  ) {
    super(message);
    this.name = "BlockchainError";
  }
}
