export const passportFixture = {
  contractor: {
    id: "contractor-1",
    legalName: "Harbor Works Ltd",
    crbRegistrationNumber: "CRB-204",
    crbCategory: "Civil works",
    crbType: "Building",
    crbClass: "II",
    crbStatus: "ACTIVE",
    crbLastVerifiedAt: "2026-09-10T10:00:00.000Z",
    crbSource: "CRB_LOOKUP",
  },
  project: {
    id: "project-1",
    contractorId: "contractor-1",
    name: "Bridge deck",
    description: "Bridge reconstruction works",
    nestTenderReference: "TN-204",
    nestContractReference: "CT-204",
    ocid: "ocds-123",
    procuringEntity: "Demo Procuring Entity",
    contractStatus: "ACTIVE",
    contractStartDate: "2026-01-01T00:00:00.000Z",
    contractEndDate: "2027-01-01T00:00:00.000Z",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-09-10T10:00:00.000Z",
  },
  milestones: [
    {
      id: "milestone-1",
      name: "Foundation",
      description: "Foundation construction milestone",
      status: "PENDING",
      policy: { id: "policy-1", name: "Inspection policy", requiredApprovals: 1, allowedRoles: ["AUDITOR"] },
      createdAt: "2026-02-01T10:00:00.000Z",
      updatedAt: "2026-02-02T10:00:00.000Z",
      evidence: [
        {
          id: "evidence-1",
          milestoneId: "milestone-1",
          status: "PENDING_VERIFICATION",
          currentVersionId: "version-2",
          createdAt: "2026-02-03T10:00:00.000Z",
          versions: [
            {
              id: "version-1",
              versionNumber: 1,
              sha256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
              createdAt: "2026-02-03T10:00:00.000Z",
              verificationStatus: "MATCH",
              verifications: [
                { id: "verification-match", status: "MATCH", source: "INTERNAL", createdAt: "2026-02-04T10:00:00.000Z" },
                { id: "verification-mismatch", status: "MISMATCH", source: "INTERNAL", createdAt: "2026-02-05T10:00:00.000Z" },
              ],
              blockchainProof: {
                id: "proof-confirmed",
                eventType: "VERIFICATION",
                referenceId: "version-1",
                evidenceHash: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                txHash: `0x${"1".repeat(64)}`,
                blockNumber: 22,
                confirmationState: "CONFIRMED",
                confirmed: true,
                createdAt: "2026-02-04T11:00:00.000Z",
              },
            },
            {
              id: "version-2",
              versionNumber: 2,
              sha256: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
              createdAt: "2026-02-06T10:00:00.000Z",
              verificationStatus: "UNAVAILABLE",
              verifications: [
                { id: "verification-pending", status: "PENDING", source: "INTERNAL", createdAt: "2026-02-07T10:00:00.000Z" },
                { id: "verification-unavailable", status: "UNAVAILABLE", source: "INTERNAL", createdAt: "2026-02-08T10:00:00.000Z" },
              ],
              blockchainProof: {
                id: "proof-pending",
                eventType: "VERIFICATION",
                referenceId: "version-2",
                evidenceHash: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
                txHash: null,
                blockNumber: null,
                confirmationState: "PENDING",
                confirmed: false,
                createdAt: "2026-02-08T11:00:00.000Z",
              },
            },
          ],
          attestations: [
            {
              id: "attestation-1",
              evidenceId: "evidence-1",
              milestoneId: "milestone-1",
              policyId: "policy-1",
              decision: "APPROVED",
              verifierRole: "AUDITOR",
              createdAt: "2026-02-09T10:00:00.000Z",
              blockchainProof: {
                id: "proof-attestation",
                eventType: "ATTESTATION",
                referenceId: "attestation-1",
                evidenceHash: null,
                txHash: `0x${"2".repeat(64)}`,
                blockNumber: 23,
                confirmationState: "CONFIRMED",
                confirmed: true,
                createdAt: "2026-02-09T11:00:00.000Z",
              },
            },
          ],
        },
      ],
      corrections: [
        {
          id: "correction-1",
          status: "RESOLVED",
          reason: "Corrected evidence reference",
          createdAt: "2026-02-10T10:00:00.000Z",
          originalRecord: {
            eventId: "proof-confirmed",
            eventType: "VERIFICATION",
            referenceId: "version-1",
            evidenceVersion: {
              id: "version-1",
              evidenceId: "evidence-1",
              versionNumber: 1,
              sha256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
              createdAt: "2026-02-03T10:00:00.000Z",
            },
            blockchainProof: {
              id: "proof-confirmed",
              eventType: "VERIFICATION",
              referenceId: "version-1",
              evidenceHash: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
              txHash: `0x${"1".repeat(64)}`,
              blockNumber: 22,
              confirmationState: "CONFIRMED",
              confirmed: true,
              createdAt: "2026-02-04T11:00:00.000Z",
            },
          },
          correctedEvidence: {
            id: "evidence-1",
            currentVersionId: "version-2",
            versions: [
              { id: "version-2", versionNumber: 2, sha256: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", createdAt: "2026-02-06T10:00:00.000Z" },
            ],
          },
          correctionProof: null,
          resolutions: [
            {
              id: "correction-resolution-1",
              status: "APPROVED",
              resolution: "Retain both evidence versions in the record.",
              resolvedById: "user-auditor",
              resolvedByRole: "AUDITOR",
              correctedEvidenceVersion: {
                id: "version-2",
                evidenceId: "evidence-1",
                versionNumber: 2,
                sha256: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
                createdAt: "2026-02-06T10:00:00.000Z",
              },
              createdAt: "2026-02-11T10:00:00.000Z",
            },
          ],
        },
      ],
    },
  ],
  variations: [
    {
      id: "variation-1",
      variationReference: "VAR-01",
      reason: "Adjusted contract scope",
      status: "APPROVED",
      createdAt: "2026-02-12T10:00:00.000Z",
      review: { reviewedById: "user-auditor", reviewedByRole: "AUDITOR", reviewedAt: "2026-02-13T10:00:00.000Z" },
      originalState: { project: { name: "Bridge deck" } },
      proposedState: { project: { name: "Bridge deck revision" } },
      milestone: { id: "milestone-1", name: "Foundation" },
      evidence: [{ id: "evidence-1", sha256: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb" }],
      previousProof: null,
      variationProof: {
        id: "proof-variation",
        eventType: "VARIATION",
        referenceId: "variation-1",
        txHash: null,
        blockNumber: null,
        confirmationState: "PENDING",
        confirmed: false,
        createdAt: "2026-02-13T11:00:00.000Z",
      },
      resolutions: [
        { id: "variation-resolution-1", status: "RESOLVED", decision: "APPROVED", note: "Recorded", resolvedById: "user-auditor", resolvedByRole: "AUDITOR", createdAt: "2026-02-13T10:00:00.000Z" },
      ],
    },
  ],
  blockchainProofs: [
    {
      id: "proof-confirmed",
      eventType: "VERIFICATION",
      referenceId: "version-1",
      evidenceHash: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      txHash: `0x${"1".repeat(64)}`,
      blockNumber: 22,
      confirmationState: "CONFIRMED",
      confirmed: true,
      createdAt: "2026-02-04T11:00:00.000Z",
    },
  ],
};